version: '3.7'

services:
    pyrocky:
        build:
            context: .
            args:
                PYCHARM_VERSION: ${PYCHARM_VERSION}
                NOMACHINE_PACKAGE_NAME: ${NOMACHINE_PACKAGE_NAME}
                NOMACHINE_BUILD: ${NOMACHINE_BUILD}
        container_name: pyrocky
        env_file:
            - .env
        environment:
            NOMACHINE_USER: ${NOMACHINE_USER}
            PASSWORD: ${PASSWORD}
            XDG_RUNTIME_DIR: /home/$NOMACHINE_USER
        ports:
            - "${NOMACHINE_PORT}:4000"
        cap_add:
            - SYS_PTRACE
